//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ilan()
        {
            this.Kayit = new HashSet<Kayit>();
        }
    
        public string ilanId { get; set; }
        public int ilanNo { get; set; }
        public int ilanFiyat { get; set; }
        public System.DateTime ilanTarihi { get; set; }
        public string ilanEmlakTipi { get; set; }
        public int ilanMetreKareBrut { get; set; }
        public int ilanMetreKareNet { get; set; }
        public int ilanOdaSayisi { get; set; }
        public int ilanBinaYasi { get; set; }
        public int ilanBulunduguKat { get; set; }
        public int ilanKatSayisi { get; set; }
        public string ilanIsitma { get; set; }
        public int ilanBanyoSayisi { get; set; }
        public int ilanBalkon { get; set; }
        public string ilanEsyali { get; set; }
        public string ilanKullanimDurumu { get; set; }
        public string ilanAidat { get; set; }
        public string ilanKimden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kayit> Kayit { get; set; }
    }
}
