//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uye__
    {
        public int uyeId { get; set; }
        public string uyeKullaniciAdi { get; set; }
        public string uyeEmail { get; set; }
        public string uyeAdSoyad { get; set; }
        public int uyeAdmin { get; set; }
        public int uyeSatici { get; set; }
    }
}
